version: '3.7'
services:
  shopping-db:
    image: mariadb
    environment: 
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
    volumes: 
      - ./data:/var/lib/mysql

  shopping-api:
    build: .
    depends_on: 
      - shopping-db
  
  web:
    image: nginx:1.16.0-alpine
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - 80:80
    command: /bin/sh -c "cat /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on: 
      - shopping-api